# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://github.com/
date_format: "ordinal"
title: reading-notes
subtitle: "Ismail Al Amir"
description: "Ismail"
keywords: python, javascript 
timezone: Asia/amman
encoding: "utf-8"
repository: mzlogin/mzlogin.github.io
cdn:
    jsdelivr:
        enabled: false
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Ismail Al Amir
organization: 
organization_url: 
github_username: IsmailAlamir
location: Amman, Jordan
email: isalamir@hotmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home


  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: false
        permalink: /wiki/:path/
    fragments:
        output: false
        permalink: /fragment/:path/
gitalk:
    owner: mzlogin
    repo: blog-comments
    clientID: d2e1cbbd298958076462
    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# utterances 配置参考：https://utteranc.es/
utterances:
    repo: mzlogin/blog-comments
# beaudar 配置参考：https://beaudar.lipk.org/
beaudar:
    repo: mzlogin/blog-comments
# giscus 配置参考：https://giscus.app/zh-CN
giscus:
    repo: mzlogin/blog-comments
    repo-id: MDEwOlJlcG9zaXRvcnk5MzEyNzkxNw==
    category: Announcements
    category-id: DIC_kwDOBY0E7c4CRtg9
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10
